name: Playwright End-to-End Tests
on:
  push:
    branches: [ main, master ]
  # Вот эта штука добавляет кнопку "Run workflow" в интерфейсе GitHub
  workflow_dispatch:

jobs:
  # СТАДИЯ 1: Подготовка окружения
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5 # обновил версию, чтобы ушли ворнинги
        with:
          python-version: '3.10'
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: pip install -r requirements.txt

  # СТАДИЯ 2: Запуск тестов (начнется только после успеха первой)
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps and Playwright
        run: |
          pip install -r requirements.txt
          # Устанавливаем и pytest-html для красивого отчета
          pip install pytest-html
          python -m playwright install --with-deps

      - name: Run Tests
        env:
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}
        # Добавляем создание HTML-отчета
        run: pytest --html=report.html --self-contained-html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html